workflow:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/*"

github:
  - changed-files:
      - any-glob-to-any-file: ".github/*"

documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]

backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "app/**"

app:
  - changed-files:
      - any-glob-to-any-file: "app/**"

docker:
  - changed-files:
      - any-glob-to-any-file: ["Dockerfile", ".dockerignore"]

dependencies:
  - changed-files:
      - any-glob-to-any-file: ["**/packages.lock.json", "**/package-lock.json"]
